name: Build All
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - uses: actions/setup-java@v4.7.1
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Add execution right to gradlew
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Install Android SDK
        run: sdkmanager "platform-tools" "platforms;android-36"

      - name: Build the library
        run: ./gradlew build --no-daemon --stacktrace --info --scan

      - name: Check bump
        id: vbump
        uses: rgryta/Check-Bump@main
        with:
          method: 'regex'
          path: 'api-client/version.properties'
          prefix: 'v'